### ISSUE TITLE
No trimmed read files were identified to run SPAdes

### ISSUE THREAD

**Issue by ef391** [mrmckain/Fast-Plast#40]
Hello, I have the same problem with the one in issue #13

"Samples for All are not in current GenBank plastomes. Using one representative from each order to make bowtie2 indices.
		******************ERROR: No trimmed read files were identified to run SPAdes.  Please check 1_Trimmed_Reads.******************"

I tried to follow the recommendations in issue #13, it seems the bowtie2 folder does not contain the indices.. I tried to re-install but the problem persists.

Could you please advise?

Many thanks
E

**Comment by mrmckain** [comment]
Hi,

When you installed, did you give Fast-Plast the full path to your bowtie2 installation? Or did you have Fast-Plast install it for you?

Best,
Michael

**Comment by ef391** [comment]
Hi Michael 

Happy New Year and thanks for your quick response!

I had the Fast-Plast install it for me... I checked the fast-plast.pl and it seems the path is correct I think: 
my $BOWTIE2="/Users/EF/Fast-Plast/bin/bowtie2-2.2.9/bowtie2"; #path to bowtie2 executable


E

**Comment by mrmckain** [comment]
Could you post some of the error outputs for me? Thanks!

**Comment by ef391** [comment]
Thu Jan  2 09:49:41 2020	Starting Fast-Plast v.1.2.8.
				Assemblying plastome with 0 single end libraries and 1 paired end libraries.
Thu Jan  2 09:49:41 2020	Determining best kmer sizes.
				K-mer sizes for SPAdes set at 55,69,87.
Thu Jan  2 09:49:41 2020	Starting read trimming with Trimmomatic.
				Using /Users/EF/Fast-Plast/bin/Trimmomatic-0.36//trimmomatic-0.36.jar.
Thu Jan  2 09:50:43 2020	Starting read mapping with bowtie2.
				Using /Users/EF/Fast-Plast/bin/bowtie2-2.2.9/bowtie2.
				Samples for All are not in current GenBank plastomes. Using one representative from each order to make bowtie2 indices.
Thu Jan  2 09:50:45 2020	Starting initial assembly with SPAdes.
				Using /Users/EF/Fast-Plast/bin/SPAdes-3.11.1-Linux/bin/spades.py.
		******************ERROR: No mapped reads files were identified to run SPAdes.  Please check 2_Bowtie_Mapping.******************

**Comment by ef391** [comment]
TrimmomaticPE: Started with arguments:
 -threads 4 /Users/EF/Bartramia_2747_GCCAAT_L007_R1_001.fastq /Users/EF/Bartramia_2747_GCCAAT_L007_R2_001.fastq Bartramia2_0.trimmed_P1.fq Bartramia2_0.trimmed_U1.fq Bartramia2_0.trimmed_P2.fq Bartramia2_0.trimmed_U2.fq ILLUMINACLIP:/Users/EF/Fast-Plast/bin/adapters/NEB-PE.fa:1:30:10 SLIDINGWINDOW:10:20 MINLEN:40
Using Long Clipping Sequence: 'ACACTCTTTCCCTACACGACGCTCTTCCGATC'
Using Long Clipping Sequence: 'GATCGGAAGAGCACACGTCTGAACTCCAGTC'
ILLUMINACLIP: Using 0 prefix pairs, 2 forward/reverse sequences, 0 forward only sequences, 0 reverse only sequences
Quality encoding detected as phred33
Input Read Pairs: 6097933 Both Surviving: 3210074 (52.64%) Forward Only Surviving: 974423 (15.98%) Reverse Only Surviving: 469372 (7.70%) Dropped: 1444064 (23.68%)
TrimmomaticPE: Completed successfully
Traceback (most recent call last):
  File "/Users/EF/Fast-Plast/bin/bowtie2-2.2.9/bowtie2-build", line 95, in <module>
    main()
  File "/Users/EF/Fast-Plast/bin/bowtie2-2.2.9/bowtie2-build", line 92, in main
    os.execv(build_bin_spec, argv)
OSError: [Errno 8] Exec format error
sh: /Users/EF/Fast-Plast/bin/bowtie2-2.2.9/bowtie2-align-s: cannot execute binary file
(ERR): Description of arguments failed!
Exiting now ...
No mapped reads files were identified to run SPAdes.  Please check 2_Bowtie_Mapping.

**Comment by mrmckain** [comment]
I have tried to replicate the error but cannot. Can you look in the 2_Bowtie_Mapping directory and tell me if there is a file called All.fsa and .bt2 files? Are there map files in that directory as well?
